### PR TITLE
Add support for multiple instance acceleration structures

### PR DESCRIPTION
**Pull request by natevm**
This PR modifies how GPRT constructs its shader binding table.

Previously, multiple instance acceleration structures would cause a crash. 

Now, when we build our SBT, we iterate over all top level acceleration structures, then iterate over all geometry of all bottom level structures in that top level, inserting a hit record for each. 

Instance acceleration structure construction now uses the instance SBT offset in order to allow for multiple instance acceleration structures to reference records in the same SBT.

To demonstrate this, this PR also adds a little demo with one tree containing triangle geometry, and another tree containing user geometry (a volumetric tetrahedron). We use both trees in the same ray generation program.

### CODE REVIEW

**Comment by natevm** [comment]
We should check to make sure all previous GPRT examples still work

**Comment by natevm** [comment]
Int 04, 05, and 07 appear to be broken... So we'll have to investigate what's going on there before merging...

**Comment by pshriwise** [comment]
Getting one error here on Linux for the `int04_computeAABBs` example:

```
Available Vulkan devices
Device [0] : NVIDIA RTX A4000
 Type: DISCRETE_GPU
 API: 1.3.194
Device [1] : llvmpipe (LLVM 14.0.0, 256 bits)
 Type: CPU
 API: 1.3.224
Geom type is being made!
Ray gen is being made!
Miss program is being made!
Compute program is being made!
failed to wait for queue idle! : 
ERROR_DEVICE_LOST
```

**Review by pshriwise — APPROVED** [review]
Tried all of the samples out on linux locally and they work well. The `h5m-reader` worked with these changes too.

**Pull request merged**
